name: 2b2t-common
main: org.cn2b2t.common.Main
version: 1.0.0 - SNAPSHOT
authors:
  - Moci
  - cn2b2t
depend:
  - 2b2t-core
commands:
  donate:
  ignore:
  settings:
  toggle:
  help:
  delay:
  speak: