name: 2b2t-death
main: org.cn2b2t.functions.death.Main
version: 1.0.0 - SNAPSHOT
authors:
  - Moci
  - cn2b2t
depend:
  - 2b2t-core
  - 2b2t-common
commands:
  suicide:
    aliases:
      - kill
      - killme